model_list:
  - model_name: bedrock-chat
    litellm_params:
      model: os.environ/BEDROCK_LITELLM_MODEL
      aws_region_name: os.environ/AWS_REGION

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
